import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import Navbar from '../components/navbar'
import AuthProvider from '../providers/authProvider'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={inter.className}>

        <>
        <Navbar />
          {children}
          </>

        </body>
      </AuthProvider>
    </html>
  )
}
